<?php

namespace mainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends EntityRepository {

    public function findRate($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT avg(e.evaluation) FROM mainBundle\Entity\Evaluation  e WHERE e.idproduit = $id");
        $result = $query->getResult();

        return $result;
    }

}
