mainBundle\Entity\Achat:
    type: entity
    table: achat
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: date
            nullable: false
            comment: ''
        idmembre:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        produits:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        total:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
    lifecycleCallbacks: {  }
