mainBundle\Entity\Administrateur:
    type: entity
    table: administrateur
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        mdp:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
