mainBundle\Entity\Evaluation:
    type: entity
    table: evaluation
    repositoryClass: mainBundle\Entity\EvaluationRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        evaluation:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        commentaire:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        date:
            type: date
            nullable: false
            comment: ''
        idproduit:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        idservice:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        idmembre:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
