mainBundle\Entity\Membre:
    type: entity
    table: membre
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        mdp:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        age:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        numerotel:
            type: string
            nullable: false
            length: 8
            fixed: false
            comment: ''
        adresse:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        bonus:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        dvisite:
            type: date
            nullable: false
            comment: ''
        type:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        nbProdVendu:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: nb_prod_vendu
    lifecycleCallbacks: {  }
