back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

main:
    resource: "@mainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
